server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/bailuning?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root


# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  type-aliases-package: com.bailuning.operation.entity


logging:
  config: classpath:logback.xml

application:
  message: Hello World
